# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flashCard_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1052, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.currentCard = QtWidgets.QTextEdit(self.centralwidget)
        self.currentCard.setGeometry(QtCore.QRect(110, 70, 641, 251))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(144)
        font.setBold(True)
        font.setWeight(75)
        self.currentCard.setFont(font)
        self.currentCard.setReadOnly(False)
        self.currentCard.setObjectName("currentCard")
        self.nextCard = QtWidgets.QPushButton(self.centralwidget)
        self.nextCard.setGeometry(QtCore.QRect(460, 350, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.nextCard.setFont(font)
        self.nextCard.setStyleSheet("background-color: rgb(98, 171, 255);")
        self.nextCard.setObjectName("nextCard")
        self.repeatList = QtWidgets.QListWidget(self.centralwidget)
        self.repeatList.setGeometry(QtCore.QRect(840, 50, 131, 421))
        self.repeatList.setObjectName("repeatList")
        self.repeatCard = QtWidgets.QPushButton(self.centralwidget)
        self.repeatCard.setGeometry(QtCore.QRect(170, 350, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.repeatCard.setFont(font)
        self.repeatCard.setStyleSheet("background-color: rgb(253, 135, 157);")
        self.repeatCard.setObjectName("repeatCard")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(860, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd.setGeometry(QtCore.QRect(813, 510, 201, 41))
        self.lcd.setObjectName("lcd")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(320, 440, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.start.setFont(font)
        self.start.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.start.setObjectName("start")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(820, 490, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1052, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Flashcards"))
        self.nextCard.setText(_translate("MainWindow", "NEXT CARD"))
        self.repeatCard.setText(_translate("MainWindow", "REPEAT CARD"))
        self.label.setText(_translate("MainWindow", "Repeat Cards"))
        self.start.setText(_translate("MainWindow", "START TIMER"))
        self.label_2.setText(_translate("MainWindow", "Total Time"))


